from bioptim import __version__ as bioptim_version
from setuptools import setup

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(
    name="bioptim",
    version=bioptim_version,
    author="Pariterre",
    author_email="pariterre@hotmail.com",
    description="An optimization framework for Optimal Control Programming in biomechanics",
    long_description=long_description,
    url="https://github.com/bioptim/bioptim",
    packages=[
        ".",
        "bioptim",
        "bioptim/dynamics",
        "bioptim/dynamics/fatigue",
        "bioptim/dynamics/state_space_dynamics",
        "bioptim/examples",
        "bioptim/examples/getting_started",
        "bioptim/examples/models",
        "bioptim/examples/models/mesh",
        "bioptim/examples/toy_examples",
        "bioptim/examples/toy_examples/acados",
        "bioptim/examples/toy_examples/custom_model",
        "bioptim/examples/toy_examples/custom_model/custom_package",
        "bioptim/examples/toy_examples/discrete_mechanics_and_optimal_control",
        "bioptim/examples/toy_examples/fatigue",
        "bioptim/examples/toy_examples/feature_examples",
        "bioptim/examples/toy_examples/holonomic_constraints",
        "bioptim/examples/toy_examples/inverse_optimal_control",
        "bioptim/examples/toy_examples/moving_horizon_estimation",
        "bioptim/examples/toy_examples/muscle_driven_ocp",
        "bioptim/examples/toy_examples/muscle_driven_with_contact",
        "bioptim/examples/toy_examples/optimal_time_ocp",
        "bioptim/examples/toy_examples/sqp_method",
        "bioptim/examples/toy_examples/stochastic_optimal_control",
        "bioptim/examples/toy_examples/symmetrical_torque_driven_ocp",
        "bioptim/examples/toy_examples/torque_driven_ocp",
        "bioptim/examples/toy_examples/tracking",
        "bioptim/gui",
        "bioptim/interfaces",
        "bioptim/limits",
        "bioptim/misc",
        "bioptim/models",
        "bioptim/models/biorbd",
        "bioptim/models/protocols",
        "bioptim/optimization",
        "bioptim/optimization/solution",
        "examples",
        "external/biomechanics_models/Geometry_triangle",
    ],
    license="LICENSE",
    keywords=["biorbd", "Ipopt", "CasADi", "Optimal control", "biomechanics"],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
    ],
    include_package_data=True,
    python_requires=">=3.7",
    zip_safe=False,
)
