from setuptools import setup

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(
    name="bioptim",
    version="2.1.0",
    author="Pariterre",
    author_email="pariterre@hotmail.com",
    description="An optimization framework for Optimal Control Programming in biomechanics",
    long_description=long_description,
    url="https://github.com/bioptim/bioptim",
    packages=[
        "bioptim",
        "bioptim/dynamics",
        "bioptim/dynamics/fatigue",
        "bioptim/gui",
        "bioptim/interfaces",
        "bioptim/limits",
        "bioptim/misc",
        "bioptim/optimization",
        "examples",
        "examples/acados",
        "examples/acados/models",
        "examples/acados/models/mesh",
        "examples/fatigue",
        "examples/fatigue/models",
        "examples/fatigue/models/mesh",
        "examples/getting_started",
        "examples/getting_started/models",
        "examples/getting_started/models/mesh",
        "examples/moving_horizon_estimation",
        "examples/moving_horizon_estimation/models",
        "examples/moving_horizon_estimation/models/mesh",
        "examples/muscle_driven_ocp",
        "examples/muscle_driven_ocp/models",
        "examples/muscle_driven_ocp/models/mesh",
        "examples/muscle_driven_with_contact",
        "examples/muscle_driven_with_contact/models",
        "examples/optimal_time_ocp",
        "examples/optimal_time_ocp/models",
        "examples/optimal_time_ocp/models/mesh",
        "examples/symmetrical_torque_driven_ocp",
        "examples/symmetrical_torque_driven_ocp/models",
        "examples/torque_driven_ocp",
        "examples/torque_driven_ocp/models",
        "examples/torque_driven_ocp/models/mesh",
        "examples/track",
        "examples/track/models",
        "examples/",
    ],
    license="LICENSE",
    keywords=["biorbd", "Ipopt", "CasADi", "Optimal control", "biomechanics"],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
    ],
    python_requires=">=3.7",
    zip_safe=False,
)
